"""v263 - the whole portal, generated for real and checked end to end.

portal_gen.py runs against a private PostgreSQL loaded with the production
schema and a synthetic fleet (see conftest.py). What is checked here is what
a person would notice if a change broke the portal:

* every page that exists today is still generated (page inventory);
* every page is a complete HTML document with a title and no Python error;
* every internal link points at a generated page, a repo asset or one of
  the live apps nginx serves - no 404s from inside the portal;
* every plant in the database has its monitoring and report page, under its
  customer name;
* the states the seed plants are in (dark plant, open CRITICAL, hot
  inverter, loan, closed recon month) show up on the pages that own them;
* no em dash, no leaked None / nan.

When a page is added or removed ON PURPOSE, update
tests/portal/expected_pages.txt (one path per line, archive days as
d/<date>.html) in the same commit - that is the conscious step.
"""
from __future__ import annotations

import csv
import io
import pathlib
import re

import pytest

V2 = pathlib.Path(__file__).resolve().parents[2]
EXPECTED = V2 / "tests" / "portal" / "expected_pages.txt"
REPO_ASSETS = V2 / "server" / "assets"

# Served by nginx from the live apps or from static folders that are not
# generated by portal_gen. A link into one of these is not a broken link.
APP_PREFIXES = ("/ask/", "/account/", "/setup/", "/maintenance/", "/finance/", "/projects/",
                "/login", "/logout", "/session/", "/invoices/")
STATIC_OUTSIDE_GENERATOR = ("/favicon.png", "/favicon.ico", "/favicon.svg",
                            "/portfolio/assets/", "/assets/")
ARCHIVE = re.compile(r"/d/\d{4}-\d{2}-\d{2}\.html$")
LINK = re.compile(r"""(?:href|src)=["'](/[^"'#?]*)""")
EM = chr(0x2014)


def _norm(rel: str) -> str:
    return ARCHIVE.sub("/d/<date>.html", rel)


@pytest.fixture(scope="module")
def site(portal_site):
    out, stdout = portal_site
    files = {p.relative_to(out).as_posix(): p for p in out.rglob("*") if p.is_file()}
    return out, stdout, files


def html_pages(files):
    return {k: p for k, p in files.items() if k.endswith(".html")}


# ------------------------------------------------------------ inventory
class TestInventory:
    def test_generator_reports_what_it_wrote(self, site):
        out, stdout, files = site
        m = re.search(r"portal_gen: wrote (\d+) pages", stdout)
        assert m, stdout[-500:]
        assert int(m.group(1)) == len(files)

    def test_every_page_that_exists_today_is_still_generated(self, site):
        _, _, files = site
        got = {_norm(k) for k in files}
        want = {ln.strip() for ln in EXPECTED.read_text(encoding="utf-8").splitlines() if ln.strip()}
        missing, extra = sorted(want - got), sorted(got - want)
        assert not missing, "pages no longer generated (a feature was lost?):\n" + "\n".join(missing)
        assert not extra, ("new pages - if intended, add them to tests/portal/expected_pages.txt:\n"
                           + "\n".join(extra))

    def test_archive_days_exist_for_every_plant(self, site, psql):
        _, _, files = site
        slugs = {k.split("/")[1] for k in files if ARCHIVE.search("/" + k)}
        plants = [r[0] for r in psql("SELECT plant_key FROM plant WHERE active ORDER BY 1")]
        assert len(slugs) == len(plants)


# ------------------------------------------------------------ every page
class TestEveryPage:
    def test_each_page_is_a_complete_document(self, site):
        _, _, files = site
        bad = []
        for k, p in html_pages(files).items():
            s = p.read_text(encoding="utf-8")
            if not s.lstrip().lower().startswith("<!doctype html") or "</html>" not in s[-200:].lower():
                bad.append(f"{k}: not a complete HTML document")
            elif "<title>" not in s:
                bad.append(f"{k}: no <title>")
            elif len(s) < 300:
                bad.append(f"{k}: suspiciously small ({len(s)} B)")
        assert not bad, "\n".join(bad)

    def test_no_python_error_leaks_into_a_page(self, site):
        _, _, files = site
        bad = [k for k, p in html_pages(files).items()
               if any(x in p.read_text(encoding="utf-8") for x in ("Traceback (most recent call last)", "Error:", "KeyError"))]
        assert not bad, bad

    def test_no_none_or_nan_shown_to_a_reader(self, site):
        _, _, files = site
        pats = re.compile(r">\s*(None|nan|NaN|undefined)\s*<|\bNone (kWh|MXN|kW|%)|\bnan (kWh|MXN|kW|%)")
        bad = []
        for k, p in html_pages(files).items():
            m = pats.search(p.read_text(encoding="utf-8"))
            if m:
                bad.append(f"{k}: ...{m.group(0)}...")
        assert not bad, "\n".join(bad)

    def test_no_em_dash_anywhere(self, site):
        _, _, files = site
        bad = [k for k, p in files.items() if p.suffix in (".html", ".csv") and EM in p.read_text(encoding="utf-8")]
        assert not bad, bad

    def test_every_page_is_bilingual(self, site):
        _, _, files = site
        # redirect stubs carry no text; every real page must offer both languages
        bad = [k for k, p in html_pages(files).items()
               if "data-es=" not in (s := p.read_text(encoding="utf-8")) and "http-equiv=\"refresh\" content=\"0" not in s]
        assert not bad, bad


# ------------------------------------------------------------ links
class TestLinks:
    def test_no_internal_link_points_nowhere(self, site):
        _, _, files = site
        broken = {}
        for k, p in html_pages(files).items():
            for u in LINK.findall(p.read_text(encoding="utf-8")):
                if u == "/" or u.startswith(APP_PREFIXES) or u.startswith(STATIC_OUTSIDE_GENERATOR):
                    continue
                if u.startswith("/monitoring/assets/"):
                    if (REPO_ASSETS / u[len("/monitoring/assets/"):]).exists():
                        continue
                rel = u.lstrip("/")
                if rel in files or (rel.rstrip("/") + "/index.html") in files:
                    continue
                broken.setdefault(u, k)
        assert not broken, "broken internal links (target -> first page linking it):\n" + "\n".join(
            f"{u}  <-  {k}" for u, k in sorted(broken.items()))

    def test_the_front_door_links_every_section(self, site):
        _, _, files = site
        s = files["index.html"].read_text(encoding="utf-8")
        for sec in ("/monitoring/", "/report/", "/map/", "/maintenance/", "/finance/", "/projects/", "/setup/"):
            assert f'href="{sec}' in s, sec


# ------------------------------------------------------------ plants
class TestPlants:
    def test_every_plant_has_both_pages_under_its_customer_name(self, site, psql):
        _, _, files = site
        import sys
        sys.path.insert(0, str(V2 / "server" / "bundle"))
        import portal_chrome as C
        for (k,) in psql("SELECT plant_key FROM plant WHERE active ORDER BY 1"):
            slug = C.slug(k)
            for sec in ("monitoring", "report"):
                assert f"{sec}/{slug}/index.html" in files, (k, sec)
                # the plant code is an alias that forwards to the customer page
                alias = files[f"{sec}/{k.lower()}/index.html"].read_text(encoding="utf-8")
                assert f"/{sec}/{slug}/" in alias, (k, sec)

    def test_the_dark_plant_is_shown_offline_with_its_alert(self, site):
        _, _, files = site
        s = files["monitoring/sms/index.html"].read_text(encoding="utf-8")
        assert "Plant offline" in s

    def test_fleet_page_counts_the_open_critical(self, site):
        _, _, files = site
        s = files["monitoring/index.html"].read_text(encoding="utf-8")
        m = re.search(r"(\d+)\s*<span[^>]*>critical|(\d+) critical", s)
        assert m and int(m.group(1) or m.group(2)) >= 1

    def test_live_plant_shows_its_inverters(self, site):
        _, _, files = site
        s = files["monitoring/taigene/index.html"].read_text(encoding="utf-8")
        assert "INV-01" in s and "INV-02" in s


# ------------------------------------------------------------ reports
class TestReports:
    def test_financial_report_carries_every_ppa_asset(self, site, psql):
        _, _, files = site
        s = files["report/financial/index.html"].read_text(encoding="utf-8")
        assert 'id="tbl_assets"' in s
        # the table is drawn in the browser from embedded daily atoms; every PPA plant must be in them
        for (k,) in psql("SELECT plant_key FROM plant WHERE portfolio = 'PPA'"):
            assert f'"{k}"' in s, k

    def test_financial_range_accepts_only_iso_dates_in_the_url(self, site):
        _, _, files = site
        s = files["report/financial/index.html"].read_text(encoding="utf-8")
        assert r"/^\d{4}-\d{2}-\d{2}$/" in s          # exactly what the browser gets

    def test_recon_csv_is_a_valid_export_with_the_closed_months(self, site, psql):
        _, _, files = site
        rows = list(csv.reader(io.StringIO(files["monitoring/recon/reconciliation.csv"].read_text(encoding="utf-8"))))
        assert len(rows) > 1 and len(rows[0]) >= 5
        n_closed = int(psql("SELECT count(*) FROM reconciliation_monthly")[0][0])
        assert len(rows) - 1 >= n_closed

    def test_every_plant_report_shows_its_production(self, site):
        _, _, files = site
        s = files["report/taigene/index.html"].read_text(encoding="utf-8")
        assert "kWh" in s and ("Taigene" in s or "TAIGENE" in s)
