"""v263 - the whole portal, generated for real and checked end to end.

portal_gen.py runs against a private PostgreSQL loaded with the production
schema and a synthetic fleet (see conftest.py). What is checked here is what
a person would notice if a change broke the portal:

* every page that exists today is still generated (page inventory);
* every page is a complete HTML document with a title and no Python error;
* every internal link points at a generated page, a repo asset or one of
  the live apps nginx serves - no 404s from inside the portal;
* every plant in the database has its monitoring and report page, under its
  customer name;
* the states the seed plants are in (dark plant, open CRITICAL, hot
  inverter, loan, closed recon month) show up on the pages that own them;
* no em dash, no leaked None / nan.

When a page is added or removed ON PURPOSE, update
tests/portal/expected_pages.txt (one path per line, archive days as
d/<date>.html) in the same commit - that is the conscious step.
"""
from __future__ import annotations

import csv
import io
import pathlib
import re

import pytest

V2 = pathlib.Path(__file__).resolve().parents[2]
EXPECTED = V2 / "tests" / "portal" / "expected_pages.txt"
REPO_ASSETS = V2 / "server" / "assets"

# Served by nginx from the live apps or from static folders that are not
# generated by portal_gen. A link into one of these is not a broken link.
APP_PREFIXES = ("/ask/", "/account/", "/setup/", "/maintenance/", "/finance/", "/projects/",
                "/login", "/logout", "/session/", "/invoices/")
STATIC_OUTSIDE_GENERATOR = ("/favicon.png", "/favicon.ico", "/favicon.svg",
                            "/portfolio/assets/", "/assets/")
ARCHIVE = re.compile(r"/d/\d{4}-\d{2}-\d{2}\.html$")
LINK = re.compile(r"""(?:href|src)=["'](/[^"'#?]*)""")
EM = chr(0x2014)


def _norm(rel: str) -> str:
    return ARCHIVE.sub("/d/<date>.html", rel)


@pytest.fixture(scope="module")
def site(portal_site):
    out, stdout = portal_site
    files = {p.relative_to(out).as_posix(): p for p in out.rglob("*") if p.is_file()}
    return out, stdout, files


def html_pages(files):
    return {k: p for k, p in files.items() if k.endswith(".html")}


# ------------------------------------------------------------ inventory
class TestInventory:
    def test_generator_reports_what_it_wrote(self, site):
        out, stdout, files = site
        m = re.search(r"portal_gen: wrote (\d+) pages", stdout)
        assert m, stdout[-500:]
        assert int(m.group(1)) == len(files)

    def test_every_page_that_exists_today_is_still_generated(self, site):
        _, _, files = site
        got = {_norm(k) for k in files}
        want = {ln.strip() for ln in EXPECTED.read_text(encoding="utf-8").splitlines() if ln.strip()}
        missing, extra = sorted(want - got), sorted(got - want)
        assert not missing, "pages no longer generated (a feature was lost?):\n" + "\n".join(missing)
        assert not extra, ("new pages - if intended, add them to tests/portal/expected_pages.txt:\n"
                           + "\n".join(extra))

    def test_archive_days_exist_for_every_plant(self, site, psql):
        _, _, files = site
        slugs = {k.split("/")[1] for k in files if ARCHIVE.search("/" + k)}
        plants = [r[0] for r in psql("SELECT plant_key FROM plant WHERE active ORDER BY 1")]
        assert len(slugs) == len(plants)


# ------------------------------------------------------------ every page
class TestEveryPage:
    def test_each_page_is_a_complete_document(self, site):
        _, _, files = site
        bad = []
        for k, p in html_pages(files).items():
            s = p.read_text(encoding="utf-8")
            if not s.lstrip().lower().startswith("<!doctype html") or "</html>" not in s[-200:].lower():
                bad.append(f"{k}: not a complete HTML document")
            elif "<title>" not in s:
                bad.append(f"{k}: no <title>")
            elif len(s) < 300:
                bad.append(f"{k}: suspiciously small ({len(s)} B)")
        assert not bad, "\n".join(bad)

    def test_no_python_error_leaks_into_a_page(self, site):
        _, _, files = site
        bad = [k for k, p in html_pages(files).items()
               if any(x in p.read_text(encoding="utf-8") for x in ("Traceback (most recent call last)", "Error:", "KeyError"))]
        assert not bad, bad

    def test_no_none_or_nan_shown_to_a_reader(self, site):
        _, _, files = site
        pats = re.compile(r">\s*(None|nan|NaN|undefined)\s*<|\bNone (kWh|MXN|kW|%)|\bnan (kWh|MXN|kW|%)")
        bad = []
        for k, p in html_pages(files).items():
            m = pats.search(p.read_text(encoding="utf-8"))
            if m:
                bad.append(f"{k}: ...{m.group(0)}...")
        assert not bad, "\n".join(bad)

    def test_no_em_dash_anywhere(self, site):
        _, _, files = site
        bad = [k for k, p in files.items() if p.suffix in (".html", ".csv") and EM in p.read_text(encoding="utf-8")]
        assert not bad, bad

    def test_every_page_is_bilingual(self, site):
        _, _, files = site
        # redirect stubs carry no text; every real page must offer both languages
        bad = [k for k, p in html_pages(files).items()
               if "data-es=" not in (s := p.read_text(encoding="utf-8")) and "http-equiv=\"refresh\" content=\"0" not in s]
        assert not bad, bad


# ------------------------------------------------------------ links
class TestLinks:
    def test_no_internal_link_points_nowhere(self, site):
        _, _, files = site
        broken = {}
        for k, p in html_pages(files).items():
            for u in LINK.findall(p.read_text(encoding="utf-8")):
                if u == "/" or u.startswith(APP_PREFIXES) or u.startswith(STATIC_OUTSIDE_GENERATOR):
                    continue
                if u.startswith("/monitoring/assets/"):
                    if (REPO_ASSETS / u[len("/monitoring/assets/"):]).exists():
                        continue
                rel = u.lstrip("/")
                if rel in files or (rel.rstrip("/") + "/index.html") in files:
                    continue
                broken.setdefault(u, k)
        assert not broken, "broken internal links (target -> first page linking it):\n" + "\n".join(
            f"{u}  <-  {k}" for u, k in sorted(broken.items()))

    def test_the_front_door_links_every_section(self, site):
        _, _, files = site
        s = files["index.html"].read_text(encoding="utf-8")
        for sec in ("/monitoring/", "/report/", "/map/", "/maintenance/", "/finance/", "/projects/", "/setup/"):
            assert f'href="{sec}' in s, sec


# ------------------------------------------------------------ plants
class TestPlants:
    def test_every_plant_has_both_pages_under_its_customer_name(self, site, psql):
        _, _, files = site
        import sys
        sys.path.insert(0, str(V2 / "server" / "bundle"))
        import portal_chrome as C
        for (k,) in psql("SELECT plant_key FROM plant WHERE active ORDER BY 1"):
            slug = C.slug(k)
            for sec in ("monitoring", "report"):
                assert f"{sec}/{slug}/index.html" in files, (k, sec)
                # the plant code is an alias that forwards to the customer page
                alias = files[f"{sec}/{k.lower()}/index.html"].read_text(encoding="utf-8")
                assert f"/{sec}/{slug}/" in alias, (k, sec)

    def test_the_dark_plant_is_shown_offline_with_its_alert(self, site):
        _, _, files = site
        s = files["monitoring/sms/index.html"].read_text(encoding="utf-8")
        assert "Plant offline" in s

    def test_fleet_page_counts_the_open_critical(self, site):
        _, _, files = site
        s = files["monitoring/index.html"].read_text(encoding="utf-8")
        m = re.search(r"(\d+)\s*<span[^>]*>critical|(\d+) critical", s)
        assert m and int(m.group(1) or m.group(2)) >= 1

    def test_live_plant_shows_its_inverters(self, site):
        _, _, files = site
        s = files["monitoring/taigene/index.html"].read_text(encoding="utf-8")
        assert "INV-01" in s and "INV-02" in s


# ------------------------------------------------------------ reports
class TestReports:
    def test_financial_report_carries_every_ppa_asset(self, site, psql):
        _, _, files = site
        s = files["report/financial/index.html"].read_text(encoding="utf-8")
        assert 'id="tbl_assets"' in s
        # the table is drawn in the browser from embedded daily atoms; every PPA plant must be in them
        for (k,) in psql("SELECT plant_key FROM plant WHERE portfolio = 'PPA'"):
            assert f'"{k}"' in s, k

    def test_financial_range_accepts_only_iso_dates_in_the_url(self, site):
        _, _, files = site
        s = files["report/financial/index.html"].read_text(encoding="utf-8")
        assert r"/^\d{4}-\d{2}-\d{2}$/" in s          # exactly what the browser gets

    def test_recon_csv_is_a_valid_export_with_the_closed_months(self, site, psql):
        _, _, files = site
        rows = list(csv.reader(io.StringIO(files["monitoring/recon/reconciliation.csv"].read_text(encoding="utf-8"))))
        assert len(rows) > 1 and len(rows[0]) >= 5
        n_closed = int(psql("SELECT count(*) FROM reconciliation_monthly")[0][0])
        assert len(rows) - 1 >= n_closed

    def test_every_plant_report_shows_its_production(self, site):
        _, _, files = site
        s = files["report/taigene/index.html"].read_text(encoding="utf-8")
        assert "kWh" in s and ("Taigene" in s or "TAIGENE" in s)


# ------------------------------------------------------------ v264 losses in MXN
class TestLosses:
    """Tomasz, 2026-09-28: 'where can I see how big the impact is in MXN?'"""

    def test_the_seeded_sag_outage_is_priced_as_unavailability(self, site, psql):
        row = psql("SELECT expected_basis, lost_kwh, unavailability_kwh, underperformance_kwh, tariff_mxn, lost_mxn"
                   " FROM loss_daily WHERE plant_key = 'MEX1'"
                   " AND prod_date = (now() AT TIME ZONE 'America/Mexico_City')::date - 2")[0]
        basis, lost, unav, under, tariff, mxn = row[0], *map(float, row[1:])
        assert basis == "peers"                                   # MEX2 and MEX3 were healthy
        assert lost > 500 and unav > 0.8 * lost                   # the 0 W hours, not the panels
        assert mxn == pytest.approx(lost * tariff, abs=1)

    def test_capex_losses_are_kwh_never_pesos(self, psql):
        rows = psql("SELECT count(*) FROM loss_daily l JOIN plant p USING (plant_key)"
                    " WHERE p.portfolio = 'CAPEX' AND (l.lost_mxn IS NOT NULL OR l.tariff_mxn IS NOT NULL)")
        assert rows == [["0"]]

    def test_the_causes_add_up_to_the_loss_on_every_row(self, psql):
        bad = psql("SELECT plant_key, prod_date FROM loss_daily WHERE abs(coalesce(lost_kwh,0) - coalesce(unavailability_kwh,0)"
                   " - coalesce(overheating_kwh,0) - coalesce(underperformance_kwh,0)) > 0.2")
        assert bad == []

    def test_the_losses_page_shows_sag_with_its_money(self, site, psql):
        _, _, files = site
        s = files["monitoring/losses/index.html"].read_text(encoding="utf-8")
        lost_mxn = float(psql("SELECT sum(lost_mxn) FROM loss_daily WHERE plant_key = 'MEX1'")[0][0])
        assert "Sag" in s or "SAG" in s
        assert f"${lost_mxn:,.0f}" in s                           # the 30-day figure, to the peso
        for word in ("Unavailability", "Overheating", "Underperformance", "Expected from"):
            assert word in s, word
        assert 'id="loss-mex1"' in s                              # the day-by-day table

    def test_the_monitoring_tabs_offer_the_losses_page(self, site):
        _, _, files = site
        assert 'href="/monitoring/losses/"' in files["monitoring/index.html"].read_text(encoding="utf-8")

    def test_sags_live_page_leads_with_the_money(self, site):
        _, _, files = site
        s = files["monitoring/sag/index.html"].read_text(encoding="utf-8")
        assert "Lost to under-production" in s and "/monitoring/losses/#loss-mex1" in s

    def test_a_capex_live_page_shows_kwh_and_no_link_to_the_financial_page(self, site):
        _, _, files = site
        s = files["monitoring/sms/index.html"].read_text(encoding="utf-8")
        assert "CAPEX, not billed per kWh" in s and "/monitoring/losses/#loss-" not in s   # the tab bar is the same for all

    def test_the_7_day_table_carries_the_loss_and_its_cause(self, site, psql):
        """v266: Tomasz - 'lets also show the losses in this Last 7 days table'."""
        _, _, files = site
        s = files["monitoring/sag/index.html"].read_text(encoding="utf-8")
        table = s[s.index("Last 7 days - production"):]
        table = table[:table.index("</table>")]
        assert "Lost kWh" in table and "Lost MXN" in table and "Main cause" in table
        day, exp, lost, mxn = psql("SELECT prod_date::text, expected_kwh, lost_kwh, lost_mxn FROM loss_daily WHERE plant_key = 'MEX1'"
                                   " AND prod_date = (now() AT TIME ZONE 'America/Mexico_City')::date - 2")[0]
        row = table[table.index(day):]
        row = row[:row.index("</tr>")]
        assert f"{float(exp):,.1f}" in row                       # expected = the 100%-available figure
        assert f"{float(lost):,.0f}" in row and f"${float(mxn):,.0f}" in row
        assert "unavailability" in row

    def test_a_capex_7_day_table_has_no_pesos(self, site):
        _, _, files = site
        s = files["monitoring/sms/index.html"].read_text(encoding="utf-8")
        table = s[s.index("Last 7 days - production"):]
        table = table[:table.index("</table>")]
        assert "Main cause" in table and "$" not in table


class TestPhoneApp:
    """v268: portal.argia.com.mx/app/ - the installable phone app, from the real pipeline."""

    def test_the_app_and_its_icon_are_generated(self, site):
        _, stdout, files = site
        assert "app FAILED" not in stdout
        for rel in ("app/index.html", "app/manifest.webmanifest", "app/sw.js", "apple-touch-icon.png",
                    "app/icon-192.png", "app/icon-512.png"):
            assert rel in files, rel
        assert files["apple-touch-icon.png"].read_bytes()[:8] == b"\x89PNG\r\n\x1a\n"

    def test_ppa_plants_only_each_under_its_customer_name(self, site, psql):
        """Tomasz, 2026-09-29: 'I want to have only PPAs in the app, no need for CAPEX'."""
        _, _, files = site
        s = files["app/index.html"].read_text(encoding="utf-8")
        import sys
        sys.path.insert(0, str(V2 / "server" / "bundle"))
        import portal_chrome as C                                     # noqa: E402
        rows = psql("SELECT plant_key, portfolio FROM plant WHERE active ORDER BY 1")
        assert {r[1] for r in rows} >= {"PPA", "CAPEX"}                  # the seed has both, so the filter is exercised
        for k, portfolio in rows:
            assert (f'id="v-p-{C.slug(k)}"' in s) == (portfolio == "PPA"), (k, portfolio)
        assert "CAPEX" not in s
        shown = re.sub(r'<small class="inv">.*?</small>', "", s)      # the seed's serials embed codes; real ones do not
        shown = re.sub(r'href="[^"]*"', "", shown)                      # ticket numbers (TK-<code>-n) live only in links
        assert not re.search(r"\b(SLP[12]|GTO[12]|NL[12]|MEX[123]|QRO1|TAM1)\b", shown)

    def test_sag_screen_carries_its_loss_money(self, site, psql):
        _, _, files = site
        s = files["app/index.html"].read_text(encoding="utf-8")
        sag = s[s.index('id="v-p-sag"'):]
        sag = sag[:sag.index("</section>")]
        day, mxn = psql("SELECT prod_date::text, lost_mxn FROM loss_daily WHERE plant_key = 'MEX1'"
                        " AND prod_date = (now() AT TIME ZONE 'America/Mexico_City')::date - 2")[0]
        assert f"${float(mxn):,.0f}" in sag                          # the outage day, priced
        assert "Unavailability" in sag

    def test_the_alerts_screen_counts_exactly_the_open_ppa_alerts(self, site, psql):
        _, _, files = site
        s = files["app/index.html"].read_text(encoding="utf-8")
        (n_ppa,), = psql("SELECT count(*) FROM alert_ledger a JOIN plant p USING (plant_key)"
                         " WHERE a.state = 'OPEN' AND a.metric <> 'daily_digest' AND p.portfolio = 'PPA' AND p.active")
        (n_capex,), = psql("SELECT count(*) FROM alert_ledger a JOIN plant p USING (plant_key)"
                           " WHERE a.state = 'OPEN' AND a.metric <> 'daily_digest' AND p.portfolio = 'CAPEX'")
        assert int(n_capex) > 0                                          # the seed's dark CAPEX plant: must be left out
        al = s[s.index('id="v-alerts"'):]
        al = al[:al.index("</section>")]
        assert al.count('class="row al"') == int(n_ppa)
        assert (f'<i class="badge">{n_ppa}</i>' in s) == (int(n_ppa) > 0)

    def test_the_header_carries_the_website_logo(self, site):
        _, _, files = site
        s = files["app/index.html"].read_text(encoding="utf-8")
        header = s[s.index("<header>"):s.index("</header>")]
        assert 'class="logo" src="data:image/png;base64,' in header and 'alt="ARGIA - Smart Energy Solutions"' in header


class TestPhoneAppTickets:
    """v271: Tomasz, 2026-09-29 - 'when I click on tickets it switched to strange
    web app mode and it is not working properly'. Tickets now live in the app."""

    def app_page(self, site):
        return site[2]["app/index.html"].read_text(encoding="utf-8")

    def test_open_ppa_tickets_are_listed_with_the_same_money_as_the_ticket_page(self, site, psql):
        s = self.app_page(site)
        tk = s[s.index('id="v-tickets"'):]
        tk = tk[:tk.index("</section>")]
        (n,), = psql("SELECT count(*) FROM ticket t JOIN plant p USING (plant_key)"
                     " WHERE t.status IN ('NEW','IN_PROGRESS','WAITING','VERIFICATION') AND p.portfolio = 'PPA'")
        assert tk.count('class="row tk"') == int(n) >= 2
        want = float(psql("SELECT sum(l.lost_mxn) FROM loss_daily l, ticket t WHERE t.number = 'T-0001' AND l.plant_key = 'MEX1'"
                          " AND l.prod_date >= (t.created_at AT TIME ZONE 'America/Mexico_City')::date"
                          " AND l.prod_date < (now() AT TIME ZONE 'America/Mexico_City')::date")[0][0])
        assert want > 500 and f"${want:,.0f}" in tk                   # the SAG outage ticket, same figure as test_ticket_cost_e2e
        assert "Check datalogger connection" in tk and "INV-02 low output" in tk

    def test_the_app_links_only_to_phone_safe_pages(self, site):
        """v272: no target=_blank (iOS ignored it), no report / portal front door
        (the report turned the Home Screen app white on Tomasz's iPhone)."""
        s = self.app_page(site)
        assert "target=" not in s
        bad = [h for h in re.findall(r'<a\b[^>]*\bhref="(/[^"]*)"', s)
               if not h.startswith(("/app/", "/monitoring/", "/maintenance/"))]
        assert not bad, bad

    def test_every_portal_page_offers_the_way_back_to_the_app(self, site):
        _, _, files = site
        for rel in ("monitoring/index.html", "monitoring/sag/index.html"):
            s = files[rel].read_text(encoding="utf-8")
            assert "backapp" in s and "navigator.standalone" in s and "history.back()" in s, rel
