name: Argia History Solar Sync

on:
  schedule:
    - cron: '0 7 * * *'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11' # Podnieśliśmy wersję zgodnie z ostrzeżeniem

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Run Solar Metering
        env:
          GOOGLE_CREDENTIALS: ${{ secrets.GOOGLE_CREDENTIALS }}
          GOOGLE_SHEET_ID: ${{ secrets.GOOGLE_SHEET_ID }}
          GROWATT_USERNAME: ${{ secrets.GROWATT_USERNAME }}    
          GROWATT_PASSWORD: ${{ secrets.GROWATT_PASSWORD }}    
          HUAWEI_USERNAME: ${{ secrets.HUAWEI_USERNAME }}    
          HUAWEI_PASSWORD: ${{ secrets.HUAWEI_PASSWORD }}
        run: python backfill.py
